# Generated by Django 6.0 on 2025-12-10 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='No symbols or spaces permitted.', regex='^[^\\W\\d_]+$')])),
                ('lastName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='No symbols or spaces permitted.', regex='^[^\\W\\d_]+$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=24)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
